from pathlib import Path

p = Path('dashboard/index.html')
s = p.read_text(encoding='utf-8')
if 'Workstation 1.1' in s:
    print('dashboard already at v1.1; no change')
    raise SystemExit(0)

css = '''
.freshgrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.sev{display:grid;grid-template-columns:84px 1fr auto;gap:10px;align-items:center;padding:9px 0;border-bottom:1px solid #292c31}.sev:last-child{border-bottom:0}.sev .rank{font-size:10px;font-weight:800}.sev .why{color:#8d929b;font-size:11px}.clock{font-variant-numeric:tabular-nums}.check{display:grid;grid-template-columns:24px 1fr auto;gap:8px;align-items:center;padding:8px 0;border-bottom:1px solid #292c31}.check:last-child{border:0}.check .num{width:22px;height:22px;border-radius:50%;display:grid;place-items:center;background:#202226;font-size:10px}.eventGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.eventGrid .k b{font-size:13px}.nonbind{border:1px dashed #4b4f58;border-radius:9px;padding:9px;background:#0b0c0e}.statusline{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.positioning{display:grid;grid-template-columns:1fr 1fr;gap:8px}.positioning .k{min-height:118px}.bigstat{font-size:20px!important}.subrow{display:flex;justify-content:space-between;gap:8px;margin-top:5px;font-size:11px}.subrow span:first-child{color:#8d929b}.nextbar{height:8px;background:#26292e;border-radius:99px;overflow:hidden;margin-top:8px}.nextbar i{height:100%;display:block;background:#77a7ff;transition:width .4s}.pulse{animation:pulse 1.8s ease-in-out infinite}@keyframes pulse{0%,100%{opacity:1}50%{opacity:.58}}
'''
if '@media(max-width:900px)' not in s:
    raise RuntimeError('CSS anchor missing')
s = s.replace('@media(max-width:900px)', css + '@media(max-width:900px)', 1)
s = s.replace('@media(max-width:900px){.grid4', '@media(max-width:900px){.freshgrid{grid-template-columns:1fr 1fr}.eventGrid{grid-template-columns:1fr 1fr}.positioning{grid-template-columns:1fr}.grid4', 1)
s = s.replace('@media(max-width:620px){.nav', '@media(max-width:620px){.freshgrid,.eventGrid{grid-template-columns:1fr 1fr}.nav', 1)

insert = '''<div class="title">Freshness control</div><section class="card"><div class="freshgrid"><div class="k"><small>Local time · Yerevan</small><b id="localClock" class="clock">—</b><small>Asia/Yerevan</small></div><div class="k"><small>4H candle close</small><b id="candleClock" class="clock amber">—</b><div class="nextbar"><i id="candleBar" style="width:0"></i></div></div><div class="k"><small>H02-A06 due</small><b id="dueClock" class="clock">—</b><small id="dueState">23:00 +04:00</small></div><div class="k"><small>Old W03/W04 age</small><b id="techAge" class="clock red">—</b><small>STALE by protocol</small></div></div><div class="statusline"><span class="tag green">Context W01/W02/W05 accepted</span><span class="tag red">Technical W03/W04 STALE</span><span class="tag amber">H02 refresh READY</span><span class="tag red">W06/W07 GATED</span></div></section>
<div class="title">Public derivatives overlay · NON-BINDING</div><section class="card nonbind"><div class="positioning"><div class="k"><small>NEARUSDT positioning</small><b class="bigstat red">MIXED / CROWDED</b><div class="subrow"><span>Mark / Funding</span><b>2.2485 / -0.00416%</b></div><div class="subrow"><span>Top positions LONG</span><b>72.0% · L/S 2.57</b></div><div class="subrow"><span>Top accounts LONG</span><b>68.9% · L/S 2.21</b></div><div class="subrow"><span>Taker Buy/Sell</span><b>0.78</b></div><div class="subrow"><span>ADL Risk</span><b class="green">LOW</b></div><small>Negative Funding flip-ը crowding-ը չի չեղարկում. old thesis-ը շարունակում է VOID մնալ։</small></div><div class="k"><small>ZECUSDT positioning</small><b class="bigstat amber">SHORT-HEAVY ACCOUNTS</b><div class="subrow"><span>Mark / Funding</span><b>1029.68 / -0.00235%</b></div><div class="subrow"><span>Top positions LONG</span><b>45.9% · L/S 0.85</b></div><div class="subrow"><span>Top accounts LONG</span><b>28.0% · L/S 0.39</b></div><div class="subrow"><span>Taker Buy/Sell</span><b>1.08</b></div><div class="subrow"><span>ADL Risk</span><b class="green">LOW</b></div><small>Short-heavy positioning + buy flow-ը squeeze potential է, բայց trade signal կամ Trigger չէ։</small></div></div><p class="muted">Այս տվյալները Binance public overlay են և չեն փոխարինում W02 report-ին։ Դրանք կարող են միայն բարձրացնել caution-ը կամ ցույց տալ, որ context-ը փոխվել է։</p></section>
<div class="title">Safety severity feed</div><section class="card"><div class="sev"><span class="tag red rank">CRITICAL</span><div><b>NEAR old thesis invalidated</b><div class="why">2.152 prior 4H low &lt; 2.168 old hard invalidation. Rebound-ը thesis revival չէ։</div></div><span class="red">VOID</span></div><div class="sev"><span class="tag red rank">HIGH</span><div><b>NEAR positioning asymmetry</b><div class="why">Elevated OI + top traders strongly LONG + recent sell-dominant taker flow։</div></div><span class="red">TRAP RISK</span></div><div class="sev"><span class="tag amber rank">HIGH</span><div><b>Event Risk</b><div class="why">W05 = HIGH_MACRO_GEOPOLITICAL. Technical quality alone բավարար չէ։</div></div><span class="amber">CAUTION</span></div><div class="sev"><span class="tag amber rank">MEDIUM</span><div><b>ZEC 1036 structure unresolved</b><div class="why">Intrabar &gt;1036 observed, բայց current price վերադարձել է ներքև. fresh W03 must classify continuation vs rejection։</div></div><span class="amber">REFRESH</span></div></section>
<div class="title">Event-risk calendar · W05 protocol evidence</div><section class="card"><div class="eventGrid"><div class="k"><small>Sep 10 · 08:30 ET</small><b>PPI</b><small>scheduled volatility window</small></div><div class="k"><small>Sep 11 · 08:30 ET</small><b>CPI</b><small>inflation surprise risk</small></div><div class="k"><small>Sep 15–16</small><b>FOMC</b><small>decision Sep 16</small></div><div class="k"><small>Unscheduled</small><b>Geopolitical / Oil</b><small>headline volatility</small></div></div><p class="muted">Event dates-ը այստեղ ցուցադրվում են W05 report-ից՝ որպես protocol context։ Final trade sizing/authorization-ը պետք է նորից անցնի W06/W07։</p></section>
'''
anchor = '<div class="title">Risk հաշվիչ</div>'
if anchor not in s:
    raise RuntimeError('risk anchor missing')
s = s.replace(anchor, insert + anchor, 1)

next_actions = '''<div class="title">Հաջորդ պարտադիր protocol քայլերը</div><section class="card"><div class="check"><span class="num amber">1</span><div><b>H02-A06 claim + fresh W04/W03</b><small>20:00 4H candle-ից հետո ամբողջ technical structure-ը նորից derive անել</small></div><span class="amber">CURRENT</span></div><div class="check"><span class="num">2</span><div><b>MAIN reconciliation</b><small>ընդունել միայն same-cycle fresh reports և update անել global state-ը</small></div><span class="muted">WAIT</span></div><div class="check"><span class="num">3</span><div><b>H03 / W06 Risk</b><small>fresh thesis-ի stop, RR, volatility, crowding, event risk, exposure</small></div><span class="muted">GATED</span></div><div class="check"><span class="num">4</span><div><b>H04 / W07 Validator</b><small>անկախ adversarial validation՝ trigger/freshness/contradictions</small></div><span class="muted">GATED</span></div><div class="check"><span class="num">5</span><div><b>MAIN final decision</b><small>TRADE միայն ամբողջ evidence chain-ի PASS/compatible verdict-ներից հետո</small></div><span class="red">NOT AUTHORIZED</span></div></section>
'''
anchor2 = '<div class="title">Safety chronology</div>'
if anchor2 not in s:
    raise RuntimeError('chronology anchor missing')
s = s.replace(anchor2, next_actions + anchor2, 1)

clock_js = '''function fmtAge(ms){if(ms<0)return 'future';let m=Math.floor(ms/60000),h=Math.floor(m/60),d=Math.floor(h/24);if(d)return d+'d '+(h%24)+'h';if(h)return h+'h '+(m%60)+'m';return m+'m'}function tickFreshness(){let now=Date.now(),four=4*3600e3,next=Math.floor(now/four)*four+four,left=next-now,hh=Math.floor(left/3600e3),mm=Math.floor((left%3600e3)/60000),ss=Math.floor((left%60000)/1000);let lc=document.getElementById('localClock'),cc=document.getElementById('candleClock'),cb=document.getElementById('candleBar'),dc=document.getElementById('dueClock'),ds=document.getElementById('dueState'),ta=document.getElementById('techAge');if(lc)lc.textContent=new Intl.DateTimeFormat('hy-AM',{timeZone:'Asia/Yerevan',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(now));if(cc)cc.textContent=`${hh}h ${String(mm).padStart(2,'0')}m ${String(ss).padStart(2,'0')}s`;if(cb)cb.style.width=(100-left/four*100).toFixed(1)+'%';let due=Date.parse('2026-09-05T23:00:00+04:00'),dl=due-now;if(dc){if(dl>=0){let dh=Math.floor(dl/3600e3),dm=Math.floor((dl%3600e3)/60000),dsx=Math.floor((dl%60000)/1000);dc.textContent=`${dh}h ${String(dm).padStart(2,'0')}m ${String(dsx).padStart(2,'0')}s`;dc.className='clock amber';if(ds)ds.textContent='մինչև due'}else{dc.textContent='OVERDUE '+fmtAge(-dl);dc.className='clock red pulse';if(ds)ds.textContent='fresh-read / recovery check required'}}let tech=Date.parse('2026-09-05T17:20:00+04:00');if(ta)ta.textContent=fmtAge(now-tech)}setInterval(tickFreshness,1000);tickFreshness();'''
anchor3 = 'function calcRisk(){'
if anchor3 not in s:
    raise RuntimeError('JS anchor missing')
s = s.replace(anchor3, clock_js + anchor3, 1)
s = s.replace('Cycle 2026-09-05_08-00 · S000033 / D000014', 'Cycle 2026-09-05_08-00 · S000033 / D000014 · Workstation 1.1', 1)
p.write_text(s, encoding='utf-8')
print('dashboard upgraded to v1.1')
